apiVersion: apps/v1
kind: Deployment
metadata:
  name: renx-app
  namespace: renx-prod
  labels:
    app: renx-app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: renx-app
  template:
    metadata:
      labels:
        app: renx-app
        version: v1
    spec:
      containers:
      - name: renx-app
        image: renx/renx-app:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 8181
          name: ai-api
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: renx-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: renx-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: renx-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: renx-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: renx-logs-pvc
