import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#3B82F6',
    primaryContainer: '#DBEAFE',
    secondary: '#10B981',
    secondaryContainer: '#D1FAE5',
    tertiary: '#8B5CF6',
    tertiaryContainer: '#EDE9FE',
    surface: '#FFFFFF',
    surfaceVariant: '#F3F4F6',
    background: '#F9FAFB',
    error: '#EF4444',
    errorContainer: '#FEE2E2',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#1E3A8A',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#064E3B',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#4C1D95',
    onSurface: '#111827',
    onSurfaceVariant: '#6B7280',
    onBackground: '#111827',
    onError: '#FFFFFF',
    onErrorContainer: '#7F1D1D',
    outline: '#D1D5DB',
    outlineVariant: '#E5E7EB',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#60A5FA',
    primaryContainer: '#1E3A8A',
    secondary: '#34D399',
    secondaryContainer: '#064E3B',
    tertiary: '#A78BFA',
    tertiaryContainer: '#4C1D95',
    surface: '#1F2937',
    surfaceVariant: '#374151',
    background: '#111827',
    error: '#F87171',
    errorContainer: '#7F1D1D',
    onPrimary: '#1E3A8A',
    onPrimaryContainer: '#DBEAFE',
    onSecondary: '#064E3B',
    onSecondaryContainer: '#D1FAE5',
    onTertiary: '#4C1D95',
    onTertiaryContainer: '#EDE9FE',
    onSurface: '#F9FAFB',
    onSurfaceVariant: '#D1D5DB',
    onBackground: '#F9FAFB',
    onError: '#7F1D1D',
    onErrorContainer: '#FEE2E2',
    outline: '#6B7280',
    outlineVariant: '#4B5563',
  },
};
